[package]
name = "cpu-tester"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "cpu_tester"
path = "src/lib.rs"

[dependencies]
kagura-assembly = { path = "../assembly" }
test-runner = { package = "kagura-test-machine", path = "../../reference/rust/runtime/machines/kagura-test" }
