[package]
name = "kagura-assembly"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "kagura_assembly"
path = "src/lib.rs"

[dev-dependencies]
kagura = { path = "../../reference/rust/kagura" }
ram = { package = "kagura-ram", path = "../../reference/rust/runtime/devices/ram" }
